<?php

namespace Interim\RecruteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegimeRepository extends EntityRepository
{
}
