etat:
    path:     /
    defaults: { _controller: "RecoverErecoverBundle:Etat:index" }

etat_show:
    path:     /{id}/show
    defaults: { _controller: "RecoverErecoverBundle:Etat:show" }

etat_new:
    path:     /new
    defaults: { _controller: "RecoverErecoverBundle:Etat:new" }

etat_create:
    path:     /create
    defaults: { _controller: "RecoverErecoverBundle:Etat:create" }
    requirements: { _method: post }

etat_edit:
    path:     /{id}/edit
    defaults: { _controller: "RecoverErecoverBundle:Etat:edit" }

etat_update:
    path:     /{id}/update
    defaults: { _controller: "RecoverErecoverBundle:Etat:update" }
    requirements: { _method: post|put }

etat_delete:
    path:     /{id}/delete
    defaults: { _controller: "RecoverErecoverBundle:Etat:delete" }
    requirements: { _method: post|delete }
