image:
    path:     /
    defaults: { _controller: "RecoverErecoverBundle:Image:index" }

image_show:
    path:     /{id}/show
    defaults: { _controller: "RecoverErecoverBundle:Image:show" }

image_new:
    path:     /new
    defaults: { _controller: "RecoverErecoverBundle:Image:new" }

image_create:
    path:     /create
    defaults: { _controller: "RecoverErecoverBundle:Image:create" }
    requirements: { _method: post }

image_edit:
    path:     /{id}/edit
    defaults: { _controller: "RecoverErecoverBundle:Image:edit" }

image_update:
    path:     /{id}/update
    defaults: { _controller: "RecoverErecoverBundle:Image:update" }
    requirements: { _method: post|put }

image_delete:
    path:     /{id}/delete
    defaults: { _controller: "RecoverErecoverBundle:Image:delete" }
    requirements: { _method: post|delete }
