menu:
    path:     /
    defaults: { _controller: "RecoverErecoverBundle:Menu:index" }

menu_show:
    path:     /{id}/show
    defaults: { _controller: "RecoverErecoverBundle:Menu:show" }

menu_new:
    path:     /new
    defaults: { _controller: "RecoverErecoverBundle:Menu:new" }

menu_create:
    path:     /create
    defaults: { _controller: "RecoverErecoverBundle:Menu:create" }
    requirements: { _method: post }

menu_edit:
    path:     /{id}/edit
    defaults: { _controller: "RecoverErecoverBundle:Menu:edit" }

menu_update:
    path:     /{id}/update
    defaults: { _controller: "RecoverErecoverBundle:Menu:update" }
    requirements: { _method: post|put }

menu_delete:
    path:     /{id}/delete
    defaults: { _controller: "RecoverErecoverBundle:Menu:delete" }
    requirements: { _method: post|delete }
