parameters:
#    recover_user.example.class: Recover\UserBundle\Example

services:
#    recover_user.example:
#        class: %recover_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
