centreinteret:
    path:     /
    defaults: { _controller: "InterimRecruteBundle:CentreInteret:index" }

centreinteret_show:
    path:     /{id}/show
    defaults: { _controller: "InterimRecruteBundle:CentreInteret:show" }

centreinteret_new:
    path:     /new
    defaults: { _controller: "InterimRecruteBundle:CentreInteret:new" }

centreinteret_create:
    path:     /create
    defaults: { _controller: "InterimRecruteBundle:CentreInteret:create" }
    requirements: { _method: post }

centreinteret_edit:
    path:     /{id}/edit
    defaults: { _controller: "InterimRecruteBundle:CentreInteret:edit" }

centreinteret_update:
    path:     /{id}/update
    defaults: { _controller: "InterimRecruteBundle:CentreInteret:update" }
    requirements: { _method: post|put }

centreinteret_delete:
    path:     /{id}/delete
    defaults: { _controller: "InterimRecruteBundle:CentreInteret:delete" }
    requirements: { _method: post|delete }
