critere:
    path:     /
    defaults: { _controller: "InterimRecruteBundle:Critere:index" }

critere_show:
    path:     /{id}/show
    defaults: { _controller: "InterimRecruteBundle:Critere:show" }

critere_new:
    path:     /new
    defaults: { _controller: "InterimRecruteBundle:Critere:new" }

critere_create:
    path:     /create
    defaults: { _controller: "InterimRecruteBundle:Critere:create" }
    requirements: { _method: post }

critere_edit:
    path:     /{id}/edit
    defaults: { _controller: "InterimRecruteBundle:Critere:edit" }

critere_update:
    path:     /{id}/update
    defaults: { _controller: "InterimRecruteBundle:Critere:update" }
    requirements: { _method: post|put }

critere_delete:
    path:     /{id}/delete
    defaults: { _controller: "InterimRecruteBundle:Critere:delete" }
    requirements: { _method: post|delete }
