personne:
    path:     /
    defaults: { _controller: "InterimRecruteBundle:Personne:index" }

personne_show:
    path:     /{id}/show
    defaults: { _controller: "InterimRecruteBundle:Personne:show" }

personne_new:
    path:     /new
    defaults: { _controller: "InterimRecruteBundle:Personne:new" }

personne_create:
    path:     /create
    defaults: { _controller: "InterimRecruteBundle:Personne:create" }
    requirements: { _method: post }

personne_edit:
    path:     /{id}/edit
    defaults: { _controller: "InterimRecruteBundle:Personne:edit" }

personne_update:
    path:     /{id}/update
    defaults: { _controller: "InterimRecruteBundle:Personne:update" }
    requirements: { _method: post|put }

personne_delete:
    path:     /{id}/delete
    defaults: { _controller: "InterimRecruteBundle:Personne:delete" }
    requirements: { _method: post|delete }

personne_grid:
    path:     /grid
    defaults: { _controller: "InterimRecruteBundle:Personne:grid" }
    #requirements: {_format: (xml|json) , _method: GET}
    