societe:
    path:     /
    defaults: { _controller: "InterimRecruteBundle:Societe:index" }

societe_show:
    path:     /{id}/show
    defaults: { _controller: "InterimRecruteBundle:Societe:show" }

societe_new:
    path:     /new
    defaults: { _controller: "InterimRecruteBundle:Societe:new" }

societe_create:
    path:     /create
    defaults: { _controller: "InterimRecruteBundle:Societe:create" }
    requirements: { _method: post }

societe_edit:
    path:     /{id}/edit
    defaults: { _controller: "InterimRecruteBundle:Societe:edit" }

societe_update:
    path:     /{id}/update
    defaults: { _controller: "InterimRecruteBundle:Societe:update" }
    requirements: { _method: post|put }

societe_delete:
    path:     /{id}/delete
    defaults: { _controller: "InterimRecruteBundle:Societe:delete" }
    requirements: { _method: post|delete }
societe_grid:
    path:     /grid
    defaults: { _controller: "InterimRecruteBundle:Societe:grid" }
    #requirements: {_format: (xml|json) , _method: GET}
societe_gettable:
    path:     /gettable
    defaults: { _controller: "InterimRecruteBundle:Societe:getTable" }
    
    
societe_societeajax:
    path:     /societeajax
    defaults: { _controller: "InterimRecruteBundle:Societe:societeajax" }
    
    