parameters:
#    interim_recrute.example.class: Interim\RecruteBundle\Example

services:
#    interim_recrute.example:
#        class: %interim_recrute.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


    sg_datatables.post:
        class: Sg\BlogBundle\Datatables\PostDatatable
        tags:
            - { name: sg.datatable.view }