competence:
    path:     /
    defaults: { _controller: "RecrutErecrutementBundle:Competence:index" }

competence_show:
    path:     /{id}/show
    defaults: { _controller: "RecrutErecrutementBundle:Competence:show" }

competence_new:
    path:     /new
    defaults: { _controller: "RecrutErecrutementBundle:Competence:new" }

competence_create:
    path:     /create
    defaults: { _controller: "RecrutErecrutementBundle:Competence:create" }
    requirements: { _method: post }

competence_edit:
    path:     /{id}/edit
    defaults: { _controller: "RecrutErecrutementBundle:Competence:edit" }

competence_update:
    path:     /{id}/update
    defaults: { _controller: "RecrutErecrutementBundle:Competence:update" }
    requirements: { _method: post|put }

competence_delete:
    path:     /{id}/delete
    defaults: { _controller: "RecrutErecrutementBundle:Competence:delete" }
    requirements: { _method: post|delete }
