experience:
    path:     /
    defaults: { _controller: "RecrutErecrutementBundle:Experience:index" }

experience_show:
    path:     /{id}/show
    defaults: { _controller: "RecrutErecrutementBundle:Experience:show" }

experience_new:
    path:     /new
    defaults: { _controller: "RecrutErecrutementBundle:Experience:new" }

experience_create:
    path:     /create
    defaults: { _controller: "RecrutErecrutementBundle:Experience:create" }
    requirements: { _method: post }

experience_edit:
    path:     /{id}/edit
    defaults: { _controller: "RecrutErecrutementBundle:Experience:edit" }

experience_update:
    path:     /{id}/update
    defaults: { _controller: "RecrutErecrutementBundle:Experience:update" }
    requirements: { _method: post|put }

experience_delete:
    path:     /{id}/delete
    defaults: { _controller: "RecrutErecrutementBundle:Experience:delete" }
    requirements: { _method: post|delete }
