poste:
    path:     /
    defaults: { _controller: "RecrutErecrutementBundle:Poste:index" }

poste_show:
    path:     /{id}/show
    defaults: { _controller: "RecrutErecrutementBundle:Poste:show" }

poste_new:
    path:     /new
    defaults: { _controller: "RecrutErecrutementBundle:Poste:new" }

poste_create:
    path:     /create
    defaults: { _controller: "RecrutErecrutementBundle:Poste:create" }
    requirements: { _method: post }

poste_edit:
    path:     /{id}/edit
    defaults: { _controller: "RecrutErecrutementBundle:Poste:edit" }

poste_update:
    path:     /{id}/update
    defaults: { _controller: "RecrutErecrutementBundle:Poste:update" }
    requirements: { _method: post|put }

poste_delete:
    path:     /{id}/delete
    defaults: { _controller: "RecrutErecrutementBundle:Poste:delete" }
    requirements: { _method: post|delete }
