groupe:
    path:     /
    defaults: { _controller: "InterimUserBundle:Groupe:index" }

groupe_show:
    path:     /{id}/show
    defaults: { _controller: "InterimUserBundle:Groupe:show" }

groupe_new:
    path:     /new
    defaults: { _controller: "InterimUserBundle:Groupe:new" }

groupe_create:
    path:     /create
    defaults: { _controller: "InterimUserBundle:Groupe:create" }
    requirements: { _method: post }

groupe_edit:
    path:     /{id}/edit
    defaults: { _controller: "InterimUserBundle:Groupe:edit" }

groupe_update:
    path:     /{id}/update
    defaults: { _controller: "InterimUserBundle:Groupe:update" }
    requirements: { _method: post|put }

groupe_delete:
    path:     /{id}/delete
    defaults: { _controller: "InterimUserBundle:Groupe:delete" }
    requirements: { _method: post|delete }
