user:
    path:     /
    defaults: { _controller: "InterimUserBundle:User:index" }
#user:
#    path:     /
#    defaults: { _controller: "InterimUserBundle:User:users" }

user_show:
    path:     /{id}/show
    defaults: { _controller: "InterimUserBundle:User:show" }

user_new:
    path:     /new
    defaults: { _controller: "InterimUserBundle:User:new" }

user_create:
    path:     /create
    defaults: { _controller: "InterimUserBundle:User:create" }
    requirements: { _method: post }

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "InterimUserBundle:User:edit" }

user_update:
    path:     /{id}/update
    defaults: { _controller: "InterimUserBundle:User:update" }
    requirements: { _method: post|put }

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "InterimUserBundle:User:delete" }
    requirements: { _method: post|delete }
    