parameters:
#    employe.example.class: Interim\EmployeBundle\Example

services:
#    employe.example:
#        class: %employe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
