<?php

namespace Recover\ErecoverBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubriqueRepository extends EntityRepository
{
}
