parameters:
#    interim_user.example.class: Interim\UserBundle\Example

services:
    interim_user.registration.form.type:
         class: Interim\UserBundle\Form\Type\RegistrationFormType
         arguments: [ %fos_user.model.user.class%]
         tags:
             - { name: form.type, alias: interim_user_registration }
